In [1]:
import datetime

In [2]:
datetime_str = '2026-08-30 18:28:56'

In [3]:
format = '%Y-%m-%d %H:%M:%S' 
datetime_dt = datetime.datetime.strptime(datetime_str, format)
print(datetime_dt)

2026-08-30 18:28:56

In [4]:
print(type(datetime_dt))

<class 'datetime.datetime'>

In [5]:
datetime_str = datetime_dt.strftime('%Y-%m-%d %H:%M:%S')

print(type(datetime_str)) # <class 'str'>
print(datetime_str)       # 2018-08-24 18:00:25

<class 'str'>
2026-08-30 18:28:56

In [6]:
datetime_str = datetime_dt.strftime('%Y-%m-%d %H')

print(type(datetime_str)) # <class 'str'>
print(datetime_str)       # 2018-08-24 18:00:25

<class 'str'>
2026-08-30 18

In [7]:
datetime_str = datetime_dt.strftime('%Y-%m')

print(type(datetime_str)) # <class 'str'>
print(datetime_str)       # 2018-08-24 18:00:25

<class 'str'>
2026-08

In [8]:
import numpy as np
np.datetime64('2019-01-01')

np.datetime64('2019-01-01')

In [9]:
np.datetime64(1000,'ns')

np.datetime64('1970-01-01T00:00:00.000001000')

In [10]:
np.datetime64(10000000000,'ns')

np.datetime64('1970-01-01T00:00:10.000000000')

In [11]:
np.datetime64(1000000000,'s')

np.datetime64('2001-09-09T01:46:40')

In [12]:
np.datetime64(10000,'D')

np.datetime64('1997-05-19')

In [13]:
np.array(['2007-07-13', '2006-01-13', '2010-08-13'], dtype='datetime64')

array(['2007-07-13', '2006-01-13', '2010-08-13'], dtype='datetime64[D]')

In [14]:
# 달단위
np.array(['2007-07-13', '2006-01-13', '2010-08-13'], dtype='datetime64[M]')

array(['2007-07', '2006-01', '2010-08'], dtype='datetime64[M]')

In [15]:
# 달단위
np.arange('2005-02', '2006-03', dtype='datetime64[M]')

array(['2005-02', '2005-03', '2005-04', '2005-05', '2005-06', '2005-07',
       '2005-08', '2005-09', '2005-10', '2005-11', '2005-12', '2006-01',
       '2006-02'], dtype='datetime64[M]')

In [16]:
# 주단위
np.arange('2005-02', '2006-03', dtype='datetime64[W]')

array(['2005-01-27', '2005-02-03', '2005-02-10', '2005-02-17',
       '2005-02-24', '2005-03-03', '2005-03-10', '2005-03-17',
       '2005-03-24', '2005-03-31', '2005-04-07', '2005-04-14',
       '2005-04-21', '2005-04-28', '2005-05-05', '2005-05-12',
       '2005-05-19', '2005-05-26', '2005-06-02', '2005-06-09',
       '2005-06-16', '2005-06-23', '2005-06-30', '2005-07-07',
       '2005-07-14', '2005-07-21', '2005-07-28', '2005-08-04',
       '2005-08-11', '2005-08-18', '2005-08-25', '2005-09-01',
       '2005-09-08', '2005-09-15', '2005-09-22', '2005-09-29',
       '2005-10-06', '2005-10-13', '2005-10-20', '2005-10-27',
       '2005-11-03', '2005-11-10', '2005-11-17', '2005-11-24',
       '2005-12-01', '2005-12-08', '2005-12-15', '2005-12-22',
       '2005-12-29', '2006-01-05', '2006-01-12', '2006-01-19',
       '2006-01-26', '2006-02-02', '2006-02-09', '2006-02-16'],
      dtype='datetime64[W]')

In [17]:
# 주단위
np.arange('2005-02', '2006-03', dtype='datetime64[W]')

array(['2005-01-27', '2005-02-03', '2005-02-10', '2005-02-17',
       '2005-02-24', '2005-03-03', '2005-03-10', '2005-03-17',
       '2005-03-24', '2005-03-31', '2005-04-07', '2005-04-14',
       '2005-04-21', '2005-04-28', '2005-05-05', '2005-05-12',
       '2005-05-19', '2005-05-26', '2005-06-02', '2005-06-09',
       '2005-06-16', '2005-06-23', '2005-06-30', '2005-07-07',
       '2005-07-14', '2005-07-21', '2005-07-28', '2005-08-04',
       '2005-08-11', '2005-08-18', '2005-08-25', '2005-09-01',
       '2005-09-08', '2005-09-15', '2005-09-22', '2005-09-29',
       '2005-10-06', '2005-10-13', '2005-10-20', '2005-10-27',
       '2005-11-03', '2005-11-10', '2005-11-17', '2005-11-24',
       '2005-12-01', '2005-12-08', '2005-12-15', '2005-12-22',
       '2005-12-29', '2006-01-05', '2006-01-12', '2006-01-19',
       '2006-01-26', '2006-02-02', '2006-02-09', '2006-02-16'],
      dtype='datetime64[W]')

In [18]:
# 일단위
np.arange('2005-02', '2005-03', dtype='datetime64[D]')

array(['2005-02-01', '2005-02-02', '2005-02-03', '2005-02-04',
       '2005-02-05', '2005-02-06', '2005-02-07', '2005-02-08',
       '2005-02-09', '2005-02-10', '2005-02-11', '2005-02-12',
       '2005-02-13', '2005-02-14', '2005-02-15', '2005-02-16',
       '2005-02-17', '2005-02-18', '2005-02-19', '2005-02-20',
       '2005-02-21', '2005-02-22', '2005-02-23', '2005-02-24',
       '2005-02-25', '2005-02-26', '2005-02-27', '2005-02-28'],
      dtype='datetime64[D]')

In [19]:
# 시간단위
np.arange('2005-02-01', '2005-02-02', dtype='datetime64[h]')

array(['2005-02-01T00', '2005-02-01T01', '2005-02-01T02', '2005-02-01T03',
       '2005-02-01T04', '2005-02-01T05', '2005-02-01T06', '2005-02-01T07',
       '2005-02-01T08', '2005-02-01T09', '2005-02-01T10', '2005-02-01T11',
       '2005-02-01T12', '2005-02-01T13', '2005-02-01T14', '2005-02-01T15',
       '2005-02-01T16', '2005-02-01T17', '2005-02-01T18', '2005-02-01T19',
       '2005-02-01T20', '2005-02-01T21', '2005-02-01T22', '2005-02-01T23'],
      dtype='datetime64[h]')

In [20]:
np.datetime64('2009-01-01') - np.datetime64('2008-01')

np.timedelta64(366,'D')

In [21]:
np.datetime64('2009-01-01') - np.datetime64('2008-01-01')

np.timedelta64(366,'D')

In [22]:
import pandas as pd

In [23]:
pd.Timestamp(1239.1238934)

Timestamp('1970-01-01 00:00:00.000001239')

In [24]:
pd.Timestamp(1239.1238934, unit='D')

Timestamp('1973-05-24 02:58:24.389760')

In [25]:
pd.Timestamp('2019-1-1')

Timestamp('2019-01-01 00:00:00')

In [26]:
pd.to_datetime('2019-1-1 12')

Timestamp('2019-01-01 12:00:00')

In [27]:
pd.to_datetime(['2018-1-1', '2019-1-2'])

DatetimeIndex(['2018-01-01', '2019-01-02'], dtype='datetime64[us]', freq=None)

In [28]:
pd.date_range('2019-01','2019-02')

DatetimeIndex(['2019-01-01', '2019-01-02', '2019-01-03', '2019-01-04',
               '2019-01-05', '2019-01-06', '2019-01-07', '2019-01-08',
               '2019-01-09', '2019-01-10', '2019-01-11', '2019-01-12',
               '2019-01-13', '2019-01-14', '2019-01-15', '2019-01-16',
               '2019-01-17', '2019-01-18', '2019-01-19', '2019-01-20',
               '2019-01-21', '2019-01-22', '2019-01-23', '2019-01-24',
               '2019-01-25', '2019-01-26', '2019-01-27', '2019-01-28',
               '2019-01-29', '2019-01-30', '2019-01-31', '2019-02-01'],
              dtype='datetime64[us]', freq='D')

In [29]:
pd.Period('2019-01')

Period('2019-01', 'M')

In [30]:
pd.Period('2019-05', freq='D')

Period('2019-05-01', 'D')

In [31]:
pd.period_range('2019-01','2019-02',freq='D')

PeriodIndex(['2019-01-01', '2019-01-02', '2019-01-03', '2019-01-04',
             '2019-01-05', '2019-01-06', '2019-01-07', '2019-01-08',
             '2019-01-09', '2019-01-10', '2019-01-11', '2019-01-12',
             '2019-01-13', '2019-01-14', '2019-01-15', '2019-01-16',
             '2019-01-17', '2019-01-18', '2019-01-19', '2019-01-20',
             '2019-01-21', '2019-01-22', '2019-01-23', '2019-01-24',
             '2019-01-25', '2019-01-26', '2019-01-27', '2019-01-28',
             '2019-01-29', '2019-01-30', '2019-01-31', '2019-02-01'],
            dtype='period[D]')

In [32]:
p = pd.Period('2019-06-13')
test = pd.Timestamp('2019-06-13 22:11')
p.start_time < test < p.end_time

True

In [33]:
p.start_time

Timestamp('2019-06-13 00:00:00')

In [34]:
p.end_time

Timestamp('2019-06-13 23:59:59.999999')

In [1]:
import FinanceDataReader as fdr

In [2]:
df_krs = fdr.StockListing('KRX')

In [3]:
type(df_krx)

NameError: name 'df_krx' is not defined

In [4]:
pip install -U finance-datareader

Requirement already satisfied: finance-datareader in C:\Anaconda\envs\tf_env\Lib\site-packages (0.9.202)
Requirement already satisfied: beautifulsoup4 in C:\Anaconda\envs\tf_env\Lib\site-packages (from finance-datareader) (4.15.0)
Requirement already satisfied: lxml in C:\Anaconda\envs\tf_env\Lib\site-packages (from finance-datareader) (6.1.2)
Requirement already satisfied: pandas>=1.1.0 in C:\Anaconda\envs\tf_env\Lib\site-packages (from finance-datareader) (3.0.5)
Requirement already satisfied: plotly in C:\Anaconda\envs\tf_env\Lib\site-packages (from finance-datareader) (7.0.0)
Requirement already satisfied: requests-file in C:\Anaconda\envs\tf_env\Lib\site-packages (from finance-datareader) (3.0.1)
Requirement already satisfied: requests>=2.3.0 in C:\Anaconda\envs\tf_env\Lib\site-packages (from finance-datareader) (2.34.2)
Requirement already satisfied: tabulate>=0.9.0 in C:\Anaconda\envs\tf_env\Lib\site-packages (from finance-datareader) (0.10.0)
Requirement already satisfied: tqdm in C:\Anaconda\envs\tf_env\Lib\site-packages (from finance-datareader) (4.70.0)
Requirement already satisfied: numpy>=1.26.0 in C:\Anaconda\envs\tf_env\Lib\site-packages (from pandas>=1.1.0->finance-datareader) (2.5.2)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Anaconda\envs\tf_env\Lib\site-packages (from pandas>=1.1.0->finance-datareader) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Anaconda\envs\tf_env\Lib\site-packages (from pandas>=1.1.0->finance-datareader) (2026.3)
Requirement already satisfied: six>=1.5 in C:\Anaconda\envs\tf_env\Lib\site-packages (from python-dateutil>=2.8.2->pandas>=1.1.0->finance-datareader) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in C:\Anaconda\envs\tf_env\Lib\site-packages (from requests>=2.3.0->finance-datareader) (3.5.1)
Requirement already satisfied: idna<4,>=2.5 in C:\Anaconda\envs\tf_env\Lib\site-packages (from requests>=2.3.0->finance-datareader) (3.19)
Requirement already satisfied: urllib3<3,>=1.26 in C:\Anaconda\envs\tf_env\Lib\site-packages (from requests>=2.3.0->finance-datareader) (2.7.0)
Requirement already satisfied: certifi>=2023.5.7 in C:\Anaconda\envs\tf_env\Lib\site-packages (from requests>=2.3.0->finance-datareader) (2026.7.22)
Requirement already satisfied: soupsieve>=1.6.1 in C:\Anaconda\envs\tf_env\Lib\site-packages (from beautifulsoup4->finance-datareader) (2.9.2)
Requirement already satisfied: typing-extensions>=4.0.0 in C:\Anaconda\envs\tf_env\Lib\site-packages (from beautifulsoup4->finance-datareader) (4.16.0)
Requirement already satisfied: narwhals>=1.15.1 in C:\Anaconda\envs\tf_env\Lib\site-packages (from plotly->finance-datareader) (2.25.0)
Requirement already satisfied: packaging in C:\Anaconda\envs\tf_env\Lib\site-packages (from plotly->finance-datareader) (26.3)
Requirement already satisfied: colorama in C:\Anaconda\envs\tf_env\Lib\site-packages (from tqdm->finance-datareader) (0.4.6)
Note: you may need to restart the kernel to use updated packages.

In [5]:
import FinanceDataReader as fdr

In [6]:
df_krx = fdr.StockListing('KRX')

In [7]:
type(df_krx)

pandas.DataFrame

In [8]:
df_krx

,Code,ISU_CD,Name,Market,Dept,Close,ChangeCode,Changes,ChagesRatio,Open,High,Low,Volume,Amount,Marcap,Stocks,MarketId
0,005930,KR7005930003,삼성전자,KOSPI,NaN,257000,2,-9000,-3.38,262500,266000,256000,15106746,3925852660500,1502493602256000,5846278608,STK
1,000660,KR7000660001,SK하이닉스,KOSPI,NaN,1653000,2,-77000,-4.45,1704000,1725000,1653000,3455018,5851249603291,1207503879345000,730492365,STK
2,005935,KR7005931001,삼성전자우,KOSPI,NaN,186800,2,-7500,-3.86,189800,192500,186200,3246546,611432364650,149882940720400,802371203,STK
3,402340,KR7402340004,SK스퀘어,KOSPI,NaN,1028000,2,-40000,-3.75,1063000,1075000,1026000,439255,459757402000,135617869944000,131923998,STK
4,009150,KR7009150004,삼성전기,KOSPI,NaN,1421000,1,36000,2.60,1398000,1460000,1393000,800641,1145352643080,106139742016000,74693696,STK
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2870,004415,KR7004411005,서울식품우,KOSPI,NaN,5470,1,100,1.86,5370,5470,5370,630,3408340,1216801500,222450,STK
2871,002785,KR7002781003,진흥기업우B,KOSPI,NaN,1336,0,0,0.00,0,0,0,0,0,1145243248,857218,STK
2872,279060,KR7279060008,이노벡스,KONEX,일반기업부,115,0,0,0.00,0,0,0,0,0,1127904590,9807866,KNX
2873,002787,KR7002782001,진흥기업2우B,KOSPI,NaN,2895,0,0,0.00,0,0,0,0,0,853469160,294808,STK
2874,032685,KR7032681009,소프트센우,KOSDAQ,중견기업부,9180,1,280,3.15,9100,9500,9100,2412,22396780,655103160,71362,KSQ

In [9]:
df_spx = fdr.StockListing('S&P500')

In [10]:
df_spx.head()

,Symbol,Name,Sector,Industry
0,MMM,3M,Industrials,Industrial Conglomerates
1,AOS,A. O. Smith,Industrials,Building Products
2,ABT,Abbott Laboratories,Health Care,Health Care Equipment
3,ABBV,AbbVie,Health Care,Biotechnology
4,ACN,Accenture,Information Technology,IT Consulting & Other Services

In [11]:
print('s&p 종목 데이터프레임의 크기 :', len(df_spx))

s&p 종목 데이터프레임의 크기 : 503

In [12]:
df = fdr.DataReader('000660', '2025')

In [13]:
df.head(10)

              Open    High     Low   Close   Volume    Change
Date
2025-01-02  170500  172200  170000  171200  2102175 -0.015526
2025-01-03  174500  182700  173100  181900  4233446  0.062500
2025-01-06  184400  199800  184400  199800  7320382  0.098406
2025-01-07  205000  206500  194800  195000  6075445 -0.024024
2025-01-08  193100  198100  191000  194700  4275792 -0.001538
2025-01-09  201000  206000  199800  205000  6692254  0.052902
2025-01-10  208000  212500  202500  203500  6149475 -0.007317
2025-01-13  203000  203000  193900  194300  4767294 -0.045209
2025-01-14  194300  197900  193600  195000  3019149  0.003603
2025-01-15  198000  201000  197700  198200  3620460  0.016410

In [14]:
df = fdr.DataReader('000660', '2026')

In [15]:
df.head(10)

              Open    High     Low   Close   Volume    Change
Date
2026-01-02  651000  679000  647000  677000  4181895  0.039939
2026-01-05  698000  700000  684000  696000  4337511  0.028065
2026-01-06  690000  727000  671000  726000  4830275  0.043103
2026-01-07  760000  762000  728000  742000  5693115  0.022039
2026-01-08  731000  788000  731000  756000  6496379  0.018868
2026-01-09  744000  756000  727000  744000  4343703 -0.015873
2026-01-12  755000  762000  735000  749000  3329793  0.006720
2026-01-13  753000  754000  724000  738000  3771944 -0.014686
2026-01-14  733000  750000  728000  742000  4885051  0.005420
2026-01-15  732000  750000  727000  749000  3003414  0.009434

In [16]:
# 애플(AAPL), 2017년
df = fdr.DataReader('AAPL', '2017')
df.head(10)

                 Open       High        Low      Close     Volume  Adj Close
2017-01-03  28.950001  29.082500  28.690001  29.037500  115127600  26.698208
2017-01-04  28.962500  29.127501  28.937500  29.004999   84472400  26.668331
2017-01-05  28.980000  29.215000  28.952499  29.152500   88774400  26.803944
2017-01-06  29.195000  29.540001  29.117500  29.477501  127007600  27.102766
2017-01-09  29.487499  29.857500  29.485001  29.747499  134247600  27.351013
2017-01-10  29.692499  29.844999  29.575001  29.777500   97848400  27.378593
2017-01-11  29.684999  29.982500  29.650000  29.937500  110354400  27.525711
2017-01-12  29.725000  29.825001  29.552500  29.812500  108344800  27.410780
2017-01-13  29.777500  29.905001  29.702499  29.760000  104447600  27.362501
2017-01-17  29.584999  30.059999  29.555000  30.000000  137759200  27.583172

In [17]:
# 애플(AAPL), 2018-01-01 ~ 2018-03-30
df = fdr.DataReader('AAPL', '2018-01-01', '2018-03-30')
df.head()

                 Open       High        Low      Close     Volume  Adj Close
2018-01-02  42.540001  43.075001  42.314999  43.064999  102223600  40.232380
2018-01-03  43.132500  43.637501  42.990002  43.057499  118071600  40.225380
2018-01-04  43.134998  43.367500  43.020000  43.257500   89738400  40.412205
2018-01-05  43.360001  43.842499  43.262501  43.750000   94640000  40.872326
2018-01-08  43.587502  43.902500  43.482498  43.587502   82271200  40.720509

In [18]:
df = fdr.DataReader('KS11', '2015')
df.head()

,Close,UpDown,Comp,Change,Open,High,Low,Volume,Amount,MarCap
Date,,,,,,,,,,
2015-01-02,1926.44,1,10.85,0.0057,1914.24,1929.15,1909.67,258775885,3696028799879,1.198010e+15
2015-01-05,1915.75,2,-10.69,-0.0055,1921.96,1921.96,1903.37,313442610,4700135929435,1.191526e+15
2015-01-06,1882.45,2,-33.30,-0.0174,1895.48,1900.02,1877.38,303687925,4755440391286,1.171167e+15
2015-01-07,1883.83,1,1.38,0.0007,1878.90,1887.60,1876.27,280509954,3762677011518,1.171991e+15
2015-01-08,1904.65,1,20.82,0.0111,1895.85,1907.23,1891.77,262207104,4395567023635,1.185170e+15

In [19]:
# 원달러 환율, 1995년~현재
df = fdr.DataReader('USD/KRW', '1995')
df.head()

,Open,High,Low,Close,Volume,Adj Close
2003-12-01,1197.300049,1203.500000,1195.000000,1198.400024,0.0,1198.400024
2003-12-02,1198.099976,1198.500000,1186.199951,1195.000000,0.0,1195.000000
2003-12-03,1195.000000,1198.400024,1192.500000,1192.500000,0.0,1192.500000
2003-12-04,1192.599976,1197.900024,1174.800049,1190.099976,0.0,1190.099976
2003-12-05,1189.400024,1193.800049,1178.599976,1184.699951,0.0,1184.699951

In [20]:
# 비트코인 원화 가격 (빗썸), 2016년~현재
df = fdr.DataReader('BTC/KRW', '2016')
df.head()

,Open,High,Low,Close,Volume,Adj Close
2015-12-31,500999.34375,508677.84375,492009.40625,505911.90625,5.404555e+10,505911.90625
2016-01-01,506092.87500,512567.25000,502287.40625,510103.59375,4.260775e+10,510103.59375
2016-01-02,510441.81250,512133.03125,507209.71875,509051.25000,3.534695e+10,509051.25000
2016-01-03,509215.68750,509409.46875,498978.56250,505155.40625,4.655981e+10,505155.40625
2016-01-04,505214.15625,517275.09375,505932.96875,514646.37500,4.572320e+10,514646.37500

In [21]:
## Quiz 1

In [22]:
import datetime
datetime_str = '07-08-2021"

SyntaxError: unterminated string literal (detected at line 2) (3780623413.py, line 2)

In [23]:
import datetime

In [24]:
datetime_str = '07-08-2021'

In [25]:
format = '%d-%m-%y'
datetime_dt = datetime.datetime.striptime(datetime_srt, format)

AttributeError: type object 'datetime.datetime' has no attribute 'striptime'

In [26]:
format = '%d-%m-%y'
datetime_dt = datetime.datetime.strptime(datetime_srt, format)

NameError: name 'datetime_srt' is not defined

In [27]:
format = '%d-%m-%y'
datetime_dt = datetime.datetime.striptime(datetime_str, format)

AttributeError: type object 'datetime.datetime' has no attribute 'striptime'

In [28]:
format = '%d-%m-%y'
datetime_dt = datetime.datetime.strptime(datetime_str, format)

ValueError: unconverted data remains: 21

In [29]:
format = '%d-%m-%Y' 
datetime_dt = datetime.datetime.strptime(datetime_str, format)
print(datetime_dt)

2021-08-07 00:00:00

In [30]:
print(type(datetime_dt))

<class 'datetime.datetime'>

In [31]:
## Quiz 2

In [32]:
## FinanceDataReader 패키지를 사용하여 미코바이오메드 종목의 2020년 1월 8일부터 2021년 7월 1일까지의 데이터를 로드 및 출력해보세요.

In [33]:
df = dfr.DataReader('214610','2020')

NameError: name 'dfr' is not defined

In [34]:
df = fdr.DataReader('214610','2020')

In [35]:
df.head(10)

             Open   High    Low  Close  Volume    Change
Date
2020-01-02  36617  38033  36617  36951     115  0.009094
2020-01-03  36951  36951  36951  36951       0  0.000000
2020-01-06  38033  38033  36951  36951      18  0.000000
2020-01-07  36951  36951  36951  36951       0  0.000000
2020-01-08  36951  36951  35858  36951      14  0.000000
2020-01-09  36951  36951  34765  36951       0  0.000000
2020-01-10  36951  39116  36399  36951      60  0.000000
2020-01-13  36930  38023  36129  36129     868 -0.022246
2020-01-14  36128  36951  34765  36899     656  0.021313
2020-01-15  36930  36930  34765  36400    1411 -0.013523

In [36]:
df = fdr.DataReader('214610', '2020-01-08', '2021-07-01')

In [37]:
df

              Open    High     Low   Close  Volume    Change
Date
2020-01-08   36951   36951   35858   36951      14  0.000000
2020-01-09   36951   36951   34765   36951       0  0.000000
2020-01-10   36951   39116   36399   36951      60  0.000000
2020-01-13   36930   38023   36129   36129     868 -0.022246
2020-01-14   36128   36951   34765   36899     656  0.021313
...            ...     ...     ...     ...     ...       ...
2021-06-25  120296  121409  117693  118818   27566  0.003166
2021-06-28  119557  121409  118058  119557   27727  0.006220
2021-06-29  121024  149617  114352  114727  541451 -0.040399
2021-06-30  114727  117319  112864  115102   53580  0.003269
2021-07-01  116205  123626  115830  120296   87041  0.045125

[368 rows x 6 columns]

In [38]:
## 파이썬 패키지 Numpy를 사용하여 2021년 3월 1일부터 2021년 7월 1일 사이의 모든 일자를 출력하세요. 단, 7월 1일도 포함해야 합니다.

In [39]:
import pandas as pd

In [40]:
pd.date_range('2021-03','2021-07')

DatetimeIndex(['2021-03-01', '2021-03-02', '2021-03-03', '2021-03-04',
               '2021-03-05', '2021-03-06', '2021-03-07', '2021-03-08',
               '2021-03-09', '2021-03-10',
               ...
               '2021-06-22', '2021-06-23', '2021-06-24', '2021-06-25',
               '2021-06-26', '2021-06-27', '2021-06-28', '2021-06-29',
               '2021-06-30', '2021-07-01'],
              dtype='datetime64[us]', length=123, freq='D')

In [41]:
import numpy as np

In [42]:
np.arange('2021-03-01', '2021-07-01', dtype = 'datetime64[D]')

array(['2021-03-01', '2021-03-02', '2021-03-03', '2021-03-04',
       '2021-03-05', '2021-03-06', '2021-03-07', '2021-03-08',
       '2021-03-09', '2021-03-10', '2021-03-11', '2021-03-12',
       '2021-03-13', '2021-03-14', '2021-03-15', '2021-03-16',
       '2021-03-17', '2021-03-18', '2021-03-19', '2021-03-20',
       '2021-03-21', '2021-03-22', '2021-03-23', '2021-03-24',
       '2021-03-25', '2021-03-26', '2021-03-27', '2021-03-28',
       '2021-03-29', '2021-03-30', '2021-03-31', '2021-04-01',
       '2021-04-02', '2021-04-03', '2021-04-04', '2021-04-05',
       '2021-04-06', '2021-04-07', '2021-04-08', '2021-04-09',
       '2021-04-10', '2021-04-11', '2021-04-12', '2021-04-13',
       '2021-04-14', '2021-04-15', '2021-04-16', '2021-04-17',
       '2021-04-18', '2021-04-19', '2021-04-20', '2021-04-21',
       '2021-04-22', '2021-04-23', '2021-04-24', '2021-04-25',
       '2021-04-26', '2021-04-27', '2021-04-28', '2021-04-29',
       '2021-04-30', '2021-05-01', '2021-05-02', '2021-05-03',
       '2021-05-04', '2021-05-05', '2021-05-06', '2021-05-07',
       '2021-05-08', '2021-05-09', '2021-05-10', '2021-05-11',
       '2021-05-12', '2021-05-13', '2021-05-14', '2021-05-15',
       '2021-05-16', '2021-05-17', '2021-05-18', '2021-05-19',
       '2021-05-20', '2021-05-21', '2021-05-22', '2021-05-23',
       '2021-05-24', '2021-05-25', '2021-05-26', '2021-05-27',
       '2021-05-28', '2021-05-29', '2021-05-30', '2021-05-31',
       '2021-06-01', '2021-06-02', '2021-06-03', '2021-06-04',
       '2021-06-05', '2021-06-06', '2021-06-07', '2021-06-08',
       '2021-06-09', '2021-06-10', '2021-06-11', '2021-06-12',
       '2021-06-13', '2021-06-14', '2021-06-15', '2021-06-16',
       '2021-06-17', '2021-06-18', '2021-06-19', '2021-06-20',
       '2021-06-21', '2021-06-22', '2021-06-23', '2021-06-24',
       '2021-06-25', '2021-06-26', '2021-06-27', '2021-06-28',
       '2021-06-29', '2021-06-30'], dtype='datetime64[D]')

In [43]:
np.arange('2021-03-01', '2021-07-02', dtype = 'datetime64[D]')

array(['2021-03-01', '2021-03-02', '2021-03-03', '2021-03-04',
       '2021-03-05', '2021-03-06', '2021-03-07', '2021-03-08',
       '2021-03-09', '2021-03-10', '2021-03-11', '2021-03-12',
       '2021-03-13', '2021-03-14', '2021-03-15', '2021-03-16',
       '2021-03-17', '2021-03-18', '2021-03-19', '2021-03-20',
       '2021-03-21', '2021-03-22', '2021-03-23', '2021-03-24',
       '2021-03-25', '2021-03-26', '2021-03-27', '2021-03-28',
       '2021-03-29', '2021-03-30', '2021-03-31', '2021-04-01',
       '2021-04-02', '2021-04-03', '2021-04-04', '2021-04-05',
       '2021-04-06', '2021-04-07', '2021-04-08', '2021-04-09',
       '2021-04-10', '2021-04-11', '2021-04-12', '2021-04-13',
       '2021-04-14', '2021-04-15', '2021-04-16', '2021-04-17',
       '2021-04-18', '2021-04-19', '2021-04-20', '2021-04-21',
       '2021-04-22', '2021-04-23', '2021-04-24', '2021-04-25',
       '2021-04-26', '2021-04-27', '2021-04-28', '2021-04-29',
       '2021-04-30', '2021-05-01', '2021-05-02', '2021-05-03',
       '2021-05-04', '2021-05-05', '2021-05-06', '2021-05-07',
       '2021-05-08', '2021-05-09', '2021-05-10', '2021-05-11',
       '2021-05-12', '2021-05-13', '2021-05-14', '2021-05-15',
       '2021-05-16', '2021-05-17', '2021-05-18', '2021-05-19',
       '2021-05-20', '2021-05-21', '2021-05-22', '2021-05-23',
       '2021-05-24', '2021-05-25', '2021-05-26', '2021-05-27',
       '2021-05-28', '2021-05-29', '2021-05-30', '2021-05-31',
       '2021-06-01', '2021-06-02', '2021-06-03', '2021-06-04',
       '2021-06-05', '2021-06-06', '2021-06-07', '2021-06-08',
       '2021-06-09', '2021-06-10', '2021-06-11', '2021-06-12',
       '2021-06-13', '2021-06-14', '2021-06-15', '2021-06-16',
       '2021-06-17', '2021-06-18', '2021-06-19', '2021-06-20',
       '2021-06-21', '2021-06-22', '2021-06-23', '2021-06-24',
       '2021-06-25', '2021-06-26', '2021-06-27', '2021-06-28',
       '2021-06-29', '2021-06-30', '2021-07-01'], dtype='datetime64[D]')

In [43]:
np.arange('2021-03-01', '2021-07-02', dtype = 'datetime64[D]')

array(['2021-03-01', '2021-03-02', '2021-03-03', '2021-03-04',
       '2021-03-05', '2021-03-06', '2021-03-07', '2021-03-08',
       '2021-03-09', '2021-03-10', '2021-03-11', '2021-03-12',
       '2021-03-13', '2021-03-14', '2021-03-15', '2021-03-16',
       '2021-03-17', '2021-03-18', '2021-03-19', '2021-03-20',
       '2021-03-21', '2021-03-22', '2021-03-23', '2021-03-24',
       '2021-03-25', '2021-03-26', '2021-03-27', '2021-03-28',
       '2021-03-29', '2021-03-30', '2021-03-31', '2021-04-01',
       '2021-04-02', '2021-04-03', '2021-04-04', '2021-04-05',
       '2021-04-06', '2021-04-07', '2021-04-08', '2021-04-09',
       '2021-04-10', '2021-04-11', '2021-04-12', '2021-04-13',
       '2021-04-14', '2021-04-15', '2021-04-16', '2021-04-17',
       '2021-04-18', '2021-04-19', '2021-04-20', '2021-04-21',
       '2021-04-22', '2021-04-23', '2021-04-24', '2021-04-25',
       '2021-04-26', '2021-04-27', '2021-04-28', '2021-04-29',
       '2021-04-30', '2021-05-01', '2021-05-02', '2021-05-03',
       '2021-05-04', '2021-05-05', '2021-05-06', '2021-05-07',
       '2021-05-08', '2021-05-09', '2021-05-10', '2021-05-11',
       '2021-05-12', '2021-05-13', '2021-05-14', '2021-05-15',
       '2021-05-16', '2021-05-17', '2021-05-18', '2021-05-19',
       '2021-05-20', '2021-05-21', '2021-05-22', '2021-05-23',
       '2021-05-24', '2021-05-25', '2021-05-26', '2021-05-27',
       '2021-05-28', '2021-05-29', '2021-05-30', '2021-05-31',
       '2021-06-01', '2021-06-02', '2021-06-03', '2021-06-04',
       '2021-06-05', '2021-06-06', '2021-06-07', '2021-06-08',
       '2021-06-09', '2021-06-10', '2021-06-11', '2021-06-12',
       '2021-06-13', '2021-06-14', '2021-06-15', '2021-06-16',
       '2021-06-17', '2021-06-18', '2021-06-19', '2021-06-20',
       '2021-06-21', '2021-06-22', '2021-06-23', '2021-06-24',
       '2021-06-25', '2021-06-26', '2021-06-27', '2021-06-28',
       '2021-06-29', '2021-06-30', '2021-07-01'], dtype='datetime64[D]')